### ISSUE TITLE
use with aliases?

### ISSUE THREAD

**Issue by AlJohri** [jezdez/envdir#63]
is there anyway to use envdir with shell aliases? for example I have a couple aliases for `django-admin` as `da` or `docker-compose` as `dc` and I would love to use them as `envdir envs/prod da migrate`

**Comment by blueyed** [comment]
zsh for example has global aliases, so that `alias -g DA=django-admin` would expand `DA` everywhere, but global aliases should be used carefully, and I would not recommend them for this purpose.

I would rather recommend to export the envdir already, for which I use this function:
```zsh
envdir-export () {
	setopt extendedglob
	local envdir=$1 
	if ! [ -d "$envdir" ]
	then
		echo "$envdir is not a dir."
		return 1
	fi
	for i in $envdir/*(.)
	do
		if [[ "${i:t}" == *.* ]]
		then
			continue
		fi
		echo "Exporting $i:t"
		eval "export ${i:t}='$(<$i)'"
	done
}
```

Or, what about having aliases like `da-prod` in the first place, for `envdir envs/prod django-admin`?

Also a generic function could be used:
```zsh
ed() {              
    local env=envs/$1; shift
    local alias_or_command=${aliases[$1]:-$1}; shift
    envdir $env ${(z)alias_or_command} "$@"
}
```

HTH ;)

**Comment by AlJohri** [comment]
super cool! I went with the `ed` function. I use something similar to your `envdir-export` (albiet hackier) but only for my local environment. prefer to be more deliberate about prod/stage commands.

storying function here for reference:

```bash
sourcelocalenvs() {
  if [ -d "envs/local" ] && test "$(ls -A "envs/local" 2>/dev/null)"; then
      echo "sourcing envs/local directory..."
      for f in envs/local/*; do
        eval $(echo export $(basename $f)=$(cat $f));
      done
  else
      echo "envs/local folder not found or is empty"
  fi
}
```
